spice_mix = set()
print(f"Initial spice mix id:, {id(spice_mix)}")
print(f"Initial spice mix id:,{spice_mix}")
spice_mix.add("cumin")
spice_mix.add("paprika")
spice_mix.add("ginger")
print(f"Initial spice mix id: {spice_mix}")
print(f"Spice mix after adding cumin and paprika: {id(spice_mix)}")